version: '3'

services:
  riotweb:
    image: bubuntux/riot-web:latest
    hostname: riotweb
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/riot-web/config.json:ro
    networks:
      - webproxy
    ports:
      - 3003:80

  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    hostname: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=${FQDN}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - POSTGRES_DB=synapse
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=G7oxxxxxxxxxxxxxV3C
      - SYNAPSE_NO_TLS=1
      - SYNAPSE_MAX_UPLOAD_SIZE=100M
    ports:
      - 3002:8008
    volumes:
      - ./files:/data
    depends_on:
      - db
    networks:
      - webproxy
    # entrypoint: ["/start.py", "migrate_config"]

  db:
    image: docker.io/postgres:12-alpine  # 10-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=G7oxxxxxxxxxxxxxV3C
    volumes:
      - ./schemas:/var/lib/postgresql/data
    networks:
      - webproxy

networks:
  webproxy:
